apiVersion: v2
name: ccv-cell-mp
description: GCP Marketplace wrapper around the ccv-cell chart
type: application
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: ccv-cell
    version: "*"
    repository: file://../../../../charts/ccv-cell
