grpcRoute:
  enabled: true
  hostname: ""
  parentRefName: ""
  parentRefNamespace: ""
  parentRefSectionName: ""

ccv-cell:
  aggregator:
    # Marketplace forbids charts from creating service accounts, it creates them and passes the name.
    serviceAccount:
      create: false
    secrets:
      app:
        type: gcpSecretStore

  verifier:
    serviceAccount:
      create: false
    secrets:
      app:
        type: gcpSecretStore
      bootstrap:
        type: gcpSecretStore
        keystoreBackend: kms
