{{- $apiKey := "00000000-0000-4000-8000-000000000001" }}
{{- $secretKey := "0000000000000000000000000000000000000000000000000000000000000001" }}
{{- $pgUser := "ccv" }}
{{- $pgPass := "ccv" }}
{{- $pgHost := "verify-postgres:5432" }}
apiVersion: v1
kind: Secret
metadata:
  name: verify-aggregator-app
type: Opaque
stringData:
  secrets.toml: |
    [storage]
    url = "postgres://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/aggregator?sslmode=disable"

    [[clients]]
    client_id = "committee-verifier-1"
    api_key = "{{ $apiKey }}"
    secret_key = "{{ $secretKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: verify-verifier-app
type: Opaque
stringData:
  secrets.toml: |
    [db]
    url = "postgres://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/verifier?sslmode=disable"

    [[aggregators]]
    secret_name = "aggregator_1"
    api_key = "{{ $apiKey }}"
    secret_key = "{{ $secretKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: verify-verifier-bootstrap
type: Opaque
stringData:
  secrets.toml: |
    [db]
    url = "postgres://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/bootstrap?sslmode=disable"

    [keystore]
    backend = "postgres"
    password = "keystore-password"
