{{- $apiKey := "00000000-0000-4000-8000-000000000001" }}
{{- $secretKey := "0000000000000000000000000000000000000000000000000000000000000001" }}
{{- $pgUser := "ccv" }}
{{- $pgPass := "ccv" }}
{{- $pgHost := "verify-postgres:5432" }}
apiVersion: v1
kind: Secret
metadata:
  name: verify-aggregator-app
type: Opaque
stringData:
  secrets.toml: |
    [storage]
    url = "postgres://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/aggregator?sslmode=disable"

    [[clients]]
    client_id = "committee-verifier-1"
    api_key = "{{ $apiKey }}"
    secret_key = "{{ $secretKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: verify-verifier-app
type: Opaque
stringData:
  secrets.toml: |
    [db]
    url = "postgres://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/verifier?sslmode=disable"

    [[aggregators]]
    secret_name = "aggregator_1"
    api_key = "{{ $apiKey }}"
    secret_key = "{{ $secretKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: verify-verifier-bootstrap
type: Opaque
stringData:
  secrets.toml: |
    [db]
    url = "postgres://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/bootstrap?sslmode=disable"

    [keystore]
    backend = "postgres"
    password = "keystore-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: verify-verifier-key-import
type: Opaque
stringData:
  key.json: |
    {"chainType":"evm","onchainPublicKey":"072cdf41f8814e23a3856591645b639f9c71de83","crypto":{"cipher":"aes-128-ctr","ciphertext":"375f050af72d8b14cf5fd90b03ebfd3989b1b79201d7009bf263db8fb0adfcebfcb327cce00e025d42ce51413e20d4e138a575396b33004d938a4457000513b1f3db6e68f56c5892b03552dac1ad934446d26ea94c226604857d1139a85e5073200c027c15f216884ff018b013f1c0da240881fa85a75f67d52d7108ddab19ca23e39756079b813e87d2567f2b72aab5da256b0decd4063b20f29fc8675bbbe150b6370d63560d8ccac13d964387eebe75a18333fd0ddf9c07b4d1c239aa5fc4a43729c0559a0eda18f29b4f8e4dedbc618e67e3ba9bcb211066493e1693bf4582158850c2cc518627e138af5b","cipherparams":{"iv":"e5a909d2e11de3ea49b5473f31ff3073"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":16384,"p":1,"r":8,"salt":"d4dace3b4401df431d04fe12a71ddef0e2426bf1fd9034fca02daa7843de97ba"},"mac":"2b92ff3c054909046826443b515f9402966d7a273f72ad60ebe61f9faacfcef3"}}
  export-password.txt: >-
    export-password
