{{- $sub := index .Subcharts "ccv-cell" }}
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "ccv-cell.selectorLabels" $sub | nindent 4 }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "chainlink-labs-ltd-public", "product_id": "chainlink-ccv-starter-kit", "partner_name": "Chainlink Labs"}'
spec:
  descriptor:
    type: CCV Cell
    version: "{{ .Chart.AppVersion }}"
    description: >-
      A Chainlink CCV Cell: a committee verifier and its aggregator.
  selector:
    matchLabels:
      {{- include "ccv-cell.selectorLabels" $sub | nindent 6 }}
  addOwnerRef: true
  componentKinds:
    - group: v1
      kind: ConfigMap
    - group: v1
      kind: Service
    - group: apps/v1
      kind: StatefulSet
    - group: secrets-store.csi.x-k8s.io
      kind: SecretProviderClass
    {{- if .Values.grpcRoute.enabled }}
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
    {{- end }}
