# See original at
# https://github.com/smartcontractkit/chainlink-ccv/blob/main/docs/config/verifier/secrets.documented.toml

[db]
url = "postgres://ccv:ccv@postgres:5432/verifier?sslmode=disable"

[[aggregators]]
secret_name = "aggregator_1"
api_key = "0fa13591-debc-42fd-ad57-e0bf5146802b"
secret_key = "01d6573b439596b0e65e727d8e79f31d37c4520f121db298dfc41271ddd37b24"
