{{- if .Values.verifier.enabled }}
{{- if eq .Values.verifier.secrets.app.type "externalSecret" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ccv-cell.secretName" (dict "root" . "component" "verifier" "subComponent" "app") }}
  labels:
    {{- include "ccv-cell.verifier.labels" . | nindent 4 }}
    {{- with .Values.verifier.secrets.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.verifier.secrets.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- toYaml .Values.verifier.secrets.app.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "ccv-cell.secretName" (dict "root" . "component" "verifier" "subComponent" "app") }}
    template:
      engineVersion: v2
      data:
        secrets.toml: |
          [db]
          url = "{{ `{{ .db_url }}` }}"

          {{- range $i, $aggregator := .Values.verifier.secrets.app.externalSecret.aggregators }}
          [[aggregators]]
          secret_name = {{ $aggregator.secretName | quote }}
          api_key = {{ print `{{ ` (printf ".aggregator_api_key_%d" $i) ` }}` | quote }}
          secret_key = {{ print `{{ ` (printf ".aggregator_secret_key_%d" $i) ` }}` | quote }}
          {{- end }}
  data:
    - secretKey: db_url
      remoteRef:
        {{- toYaml .Values.verifier.secrets.app.externalSecret.dbUrlRemoteRef | nindent 8 }}
    {{- range $i, $aggregator := .Values.verifier.secrets.app.externalSecret.aggregators }}
    - secretKey: {{ printf "aggregator_api_key_%d" $i }}
      remoteRef:
        {{- toYaml $aggregator.apiKeyRemoteRef | nindent 8 }}
    - secretKey: {{ printf "aggregator_secret_key_%d" $i }}
      remoteRef:
        {{- toYaml $aggregator.secretKeyRemoteRef | nindent 8 }}
    {{- end }}
---
{{- end }}
{{- if eq .Values.verifier.secrets.bootstrap.type "externalSecret" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ccv-cell.secretName" (dict "root" . "component" "verifier" "subComponent" "bootstrap") }}
  labels:
    {{- include "ccv-cell.verifier.labels" . | nindent 4 }}
    {{- with .Values.verifier.secrets.bootstrap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.verifier.secrets.bootstrap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- toYaml .Values.verifier.secrets.bootstrap.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "ccv-cell.secretName" (dict "root" . "component" "verifier" "subComponent" "bootstrap") }}
    template:
      engineVersion: v2
      data:
        secrets.toml: |
          [db]
          url = "{{ `{{ .db_url }}` }}"

          [keystore]
          backend = {{ .Values.verifier.secrets.bootstrap.keystoreBackend | quote }}

          {{- if eq .Values.verifier.secrets.bootstrap.keystoreBackend "postgres" }}
          password = "{{ `{{ .keystore_password }}` }}"
          {{- else if eq .Values.verifier.secrets.bootstrap.keystoreBackend "kms" }}
          [keystore.kms]
          ecdsa_key_id = {{ .Values.verifier.secrets.bootstrap.kms.ecdsaKeyId | quote }}
          ed25519_key_id = {{ .Values.verifier.secrets.bootstrap.kms.ed25519KeyId | quote }}
          {{- else }}
            {{- fail (print "Storage backend '" .Values.verifier.secrets.bootstrap.keystoreBackend "' is invalid") }}
          {{- end }}

  data:
    - secretKey: db_url
      remoteRef:
        {{- toYaml .Values.verifier.secrets.bootstrap.externalSecret.dbUrlRemoteRef | nindent 8 }}
    {{- if eq .Values.verifier.secrets.bootstrap.keystoreBackend "postgres" }}
    - secretKey: keystore_password
      remoteRef:
        {{- toYaml .Values.verifier.secrets.bootstrap.externalSecret.keystorePasswordRemoteRef | nindent 8 }}
    {{- end }}
---
{{- end }}
{{- end }}
