{{- if .Values.verifier.enabled }}
{{- range $sub := (list "app" "bootstrap" "evm") }}
{{- include "ccv-cell.secretProviderClass" (dict "root" $ "component" "verifier" "subComponent" $sub) }}
{{- end }}
{{- end }}
