{{- if .Values.aggregator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccv-cell.aggregator.fullname" . }}-config
  labels:
    {{- include "ccv-cell.aggregator.labels" . | nindent 4 }}
    {{- with .Values.aggregator.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.aggregator.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.toml: |
    [server]
    address = {{ .Values.aggregator.config.server.address | quote }}

    [healthCheck]
    port = {{ .Values.aggregator.ports.health | quote }}

    [rateLimiting]
    enabled = false

    [heartbeat]
    storeType = "memory"

    {{ .Values.aggregator.config.clients | nindent 4 }}

{{- end }}
