{{- if .Values.aggregator.enabled }}
{{- if eq .Values.aggregator.secrets.app.type "externalSecret" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ccv-cell.secretName" (dict "root" . "component" "aggregator" "subComponent" "app") }}
  labels:
    {{- include "ccv-cell.aggregator.labels" . | nindent 4 }}
    {{- with .Values.aggregator.secrets.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.aggregator.secrets.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- toYaml .Values.aggregator.secrets.app.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "ccv-cell.secretName" (dict "root" . "component" "aggregator" "subComponent" "app") }}
    template:
      engineVersion: v2
      data:
        secrets.toml: |
          [storage]
          url = "{{ `{{ .storage_url }}` }}"

          {{- range $i, $client := .Values.aggregator.secrets.app.externalSecret.clients }}
          [[clients]]
          client_id = {{ $client.clientId | quote }}
          api_key = {{ print `{{ ` (printf ".client_api_key_%d" $i) ` }}` | quote }}
          secret_key = {{ print `{{ ` (printf ".client_secret_key_%d" $i) ` }}` | quote }}
          {{- end }}
  data:
    - secretKey: storage_url
      remoteRef:
        {{- toYaml .Values.aggregator.secrets.app.externalSecret.storageUrlRemoteRef | nindent 8 }}
    {{- range $i, $client := .Values.aggregator.secrets.app.externalSecret.clients }}
    - secretKey: {{ printf "client_api_key_%d" $i }}
      remoteRef:
        {{- toYaml $client.apiKeyRemoteRef | nindent 8 }}
    - secretKey: {{ printf "client_secret_key_%d" $i }}
      remoteRef:
        {{- toYaml $client.secretKeyRemoteRef | nindent 8 }}
    {{- end }}
---
{{- end }}
{{- end }}
