{{- if and .Values.aggregator.enabled .Values.aggregator.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ccv-cell.aggregator.fullname" . }}
  labels:
    {{- include "ccv-cell.aggregator.labels" . | nindent 4 }}
    {{- with .Values.aggregator.networkPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.aggregator.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "ccv-cell.aggregator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- range .Values.aggregator.networkPolicy.ingress }}
    - {{- with .from }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ports:
        {{- if .ports }}
        {{- toYaml .ports | nindent 8 }}
        {{- else }}
        - port: grpc
        - port: health
        {{- end }}
    {{- end }}
{{- end }}
