{{- if .Values.aggregator.enabled }}
{{- $secretType := .Values.aggregator.secrets.app.type }}
{{- if or (eq $secretType "gcpSecretStore") (eq $secretType "awsSecretStore") }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ccv-cell.secretName" (dict "root" . "component" "aggregator" "subComponent" "app") }}
  labels:
    {{- include "ccv-cell.aggregator.labels" . | nindent 4 }}
    {{- with .Values.aggregator.secrets.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.aggregator.secrets.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq $secretType "gcpSecretStore" }}
  provider: gke
  parameters:
    secrets: |
      - resourceName: {{ required "aggregator.secrets.app.gcpSecretStore.secretVersionResourceName is required when aggregator.secrets.app.type is gcpSecretStore" .Values.aggregator.secrets.app.gcpSecretStore.secretVersionResourceName | quote }}
        path: "secrets.toml"
  {{- else }}
  provider: aws
  parameters:
    objects: |
      - objectName: {{ required "aggregator.secrets.app.awsSecretStore.secretName is required when aggregator.secrets.app.type is awsSecretStore" .Values.aggregator.secrets.app.awsSecretStore.secretName | quote }}
        objectType: "secretsmanager"
        objectAlias: "secrets.toml"
    {{- with .Values.aggregator.secrets.app.awsSecretStore.region }}
    region: {{ . | quote }}
    {{- end }}
    {{- if .Values.aggregator.secrets.app.awsSecretStore.usePodIdentity }}
    usePodIdentity: "true"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
