apiVersion: v2
name: ccv-cell
description: Chainlink CCIP 2.0 CCV Cell deployment, including aggregator and verifier
type: application
version: 0.0.0 # ignored, set by CI on release
kubeVersion: ">= 1.19.0-0"
keywords:
  - chainlink
  - ccip
  - ccv
  - cross-chain-verifier
home: https://github.com/smartcontractkit/chainlink-ccv-starter-kit
sources:
  - https://github.com/smartcontractkit/chainlink-ccv
